import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";
import Typed from "react-typed";
import Link from "next/link";
import ActiveLink from "../components/ActiveLink";

export default function Home() {
  return (
    <div
      className={"d-flex vh-100 text-center text-white"}
      style={{ backgroundColor: "#FFA1A9" }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={
          styles.coverContainer + " d-flex w-100 h-100 p-3 mx-auto flex-column"
        }
      >
        <header>
          <div className="d-flex justify-content-between">
            <h3 className="mb-0">Koranovel</h3>
            <nav className={styles.navMasthead + " justify-content-center"}>
              <style jsx>{`
                .selected {
                  color: #fff;
                  border-bottom: 0.25rem solid;
                  border-bottom-color: #fff;
                }
              `}</style>
              <ActiveLink href="/" activeClassName="selected">
                <a className={styles.navLink}>Home</a>
              </ActiveLink>
              <ActiveLink
                className={styles.navLink}
                href="/about"
                activeClassName="selected"
              >
                <a className={styles.navLink}>About</a>
              </ActiveLink>
              <ActiveLink
                className={styles.navLink}
                href="/novel"
                activeClassName="selected"
              >
                <a className={styles.navLink}>Novel</a>
              </ActiveLink>
            </nav>
          </div>
        </header>
        <main className="px-3 body">
          <div
            style={{
              height: "150px",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            {/* {showMessage()} */}
          </div>
          <h1>
            <Typed
              strings={["Welcome to Koranovel"]}
              typeSpeed={50}
              // backSpeed={20}
              showCursor={false}
            />
          </h1>
          <div className="home-body-text">
            <h4 className="lead">
              <Typed
                strings={[
                  "koranovel.com consist of our records and my own personal records. For those who ends up here, please kindly enjoy the website.",
                ]}
                startDelay={2100}
                typeSpeed={30}
              />
            </h4>
            <h3 className="lead">
              <Typed
                strings={["Keep Calm and Enjoy Reading"]}
                startDelay={7500}
                typeSpeed={30}
                showCursor={false}
              />
            </h3>
            <h4 className="lead">
              <Typed
                strings={["- Kartika G.M. -"]}
                startDelay={8500}
                typeSpeed={100}
                showCursor={false}
              />
            </h4>
          </div>
          <Link href="/blog">
            <a className={`btn btn-lg ${styles.btnPrimary} text-white`}>
              Kara Blog
            </a>
          </Link>
        </main>

        <footer className={"mt-auto text-white-50"}>
          <p>Created by Barly &copy; 2020 </p>
        </footer>
      </div>
    </div>
  );
}
